### ISSUE TITLE
tracking issue to ensure we have dependabot configs for our dart.dev published packages

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/ecosystem#12]
This is a tracking issue to ensure we have dependabot configs for our [dart.dev](https://pub.dev/publishers/dart.dev/packages) published packages.

- [x] https://github.com/dart-lang/args/pull/226
- [x] https://github.com/dart-lang/characters/pull/67
- [x] https://github.com/dart-lang/typed_data/pull/55
- [x] https://github.com/dart-lang/crypto/pull/136
- [x] https://github.com/dart-lang/fake_async/pull/52
- [x] https://github.com/dart-lang/ffi/pull/164
- [x] https://github.com/dart-lang/path/pull/128
- [x] https://github.com/dart-lang/fixnum/pull/94
- [x] https://github.com/dart-lang/mockito/pull/584
